import { Zen_Kaku_Gothic_New } from "next/font/google";
import "./globals.css";
import Footer from "./layout/footer";
import Header from "./layout/header";
import { classNames } from "./utils/class-names";

const font = Zen_Kaku_Gothic_New({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "OdekakeGPT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@500&family=Zen+Old+Mincho&display=swap" rel="stylesheet"></link>
      </head>
      <body className={classNames(font.className, "text-indigo-950")}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
